version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    #command: ['--replSet', 'overleaf']
    command: ['--bind_ip_all']
    volumes:
      - ~/mongo_data:/data/db
      #- ./mongodb-init-replica-set.js:/docker-entrypoint-initdb.d/mongodb-init-replica-set.js
    environment:
      MONGO_INITDB_DATABASE: sharelatex
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand({ ping: 1 })' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
  redis:
    image: redis:6.2
    container_name: redis
    volumes:
      - ~/redis_data:/data
  sharelatex:
    image: sharelatex/sharelatex
    container_name: sharelatex
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      OVERLEAF_SITE_URL: "https://overleaf.draylon.dev"
      OVERLEAF_BEHIND_PROXY: "true"
      OVERLEAF_SECURE_COOKIE: "true"
    
      OVERLEAF_APP_NAME: Overleaf Community Edition
      OVERLEAF_MONGO_URL: "mongodb://mongo/sharelatex?directConnection=true"
      OVERLEAF_REDIS_HOST: redis
      REDIS_HOST: redis
      ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
      ENABLE_CONVERSIONS: 'true'
      EMAIL_CONFIRMATION_DISABLED: 'true'
    volumes:
      - ~/sharelatex_data:/var/lib/overleaf
    ports:
      - 8010:80  # you can change 8010 to any available host port
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overleaf.rule=Host(`overleaf.draylon.dev`)"
      - "traefik.http.routers.overleaf.entrypoints=websecure"
      - "traefik.http.routers.overleaf.tls=true"
      - "traefik.http.services.overleaf.loadbalancer.server.port=80"
      - "traefik.http.middlewares.force-https.redirectscheme.scheme=https"
      - "traefik.http.routers.overleaf.middlewares=force-https"

networks:
  default:
    name: overleaf-net
