version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    command: ['--replSet', 'overleaf']
    volumes:
      - ~/mongo_data:/data/db
      - ./mongodb-init-replica-set.js:/docker-entrypoint-initdb.d/mongodb-init-replica-set.js
    environment:
      MONGO_INITDB_DATABASE: sharelatex
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 10

  redis:
    image: redis:6.2
    container_name: redis
    volumes:
      - ~/redis_data:/data

  sharelatex:
    image: sharelatex/sharelatex
    container_name: sharelatex
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      OVERLEAF_APP_NAME: Overleaf Community Edition
      OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex?replicaSet=overleaf
      OVERLEAF_REDIS_HOST: redis
      REDIS_HOST: redis
      ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
      ENABLE_CONVERSIONS: 'true'
      EMAIL_CONFIRMATION_DISABLED: 'true'
    volumes:
      - ~/sharelatex_data:/var/lib/overleaf
    ports:
      - 8010:80  # you can change 8010 to any available host port

networks:
  default:
    name: overleaf-net
